#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $CURRENT_DIR/..

echo ""
echo "***********************************************************"
echo "****              Start compiling the app              ****"
echo "***********************************************************"
echo ""

play clean compile stage

echo ""
echo "***********************************************************"
echo "****                 Done building !!!                 ****"
echo "***********************************************************"
