#!/bin/bash

GARDENCAFFE_DOCKER_NAME=gardencaffe
MONGODB_DOCKER_NAME=gardencaffe_mongodb

DATA_DIR=/www/gardencaffe/data

echo ""
echo "*****************************************************************************"
echo "****     Remove old docker images : gardencaffe, mongodb_gardencaffe     ****"
echo "*****************************************************************************"
echo ""

docker rm -f $GARDENCAFFE_DOCKER_NAME
docker rm -f $MONGODB_DOCKER_NAME

echo ""
echo "*****************************************************************************"
echo "****      Starting docker images : gardencaffe,mongodb_gardencaffe       ****"
echo "*****************************************************************************"
echo ""

docker run -d --name $MONGODB_DOCKER_NAME -e AUTH=no -v $DATA_DIR:/data/db  $MONGODB_DOCKER_NAME
docker run -d -p 9010:9010 --link $MONGODB_DOCKER_NAME:db --name $GARDENCAFFE_DOCKER_NAME $GARDENCAFFE_DOCKER_NAME

echo ""
echo "*****************************************************************************"
echo "****                     Garden Caffé is running !!!                     ****"
echo "*****************************************************************************"
echo ""
