#!/bin/bash

GARDENCAFFE_DOCKER_NAME=gardencaffe
MONGODB_DOCKER_NAME=gardencaffe_mongodb

echo ""
echo "*****************************************************************************"
echo "****      Stopping docker images : gardencaffe, mongodb_gardencaffe      ****"
echo "*****************************************************************************"
echo ""

docker stop $GARDENCAFFE_DOCKER_NAME
docker stop $MONGODB_DOCKER_NAME

echo ""
echo "*****************************************************************************"
echo "****                      Garden Caffé is DOWN !!!                       ****"
echo "*****************************************************************************"
echo ""
