#!/bin/bash

echo ""
echo "*****************************************************************************"
echo "****      Stopping docker images : gardencaffe, mongodb_gardencaffe      ****"
echo "*****************************************************************************"
echo ""

docker stop mongodb_gardencaffe
docker stop gardencaffe

echo ""
echo "*****************************************************************************"
echo "****                      Garden Caffé is DOWN !!!                       ****"
echo "*****************************************************************************"
echo ""